services:
  egresso:
    image: ghcr.io/vojkovic/egresso:latest
    container_name: egresso
    restart: unless-stopped
    privileged: true
    pid: host
    cgroup: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
